language: python
python:
  - "3.5"
  
env:
  global:
    - CODECOV_TOKEN="5c2b184f-65e6-4513-b6cd-fda33688ca81"

# command to install dependencies
install:
  - "pip install -r requirements.txt"

before-script:
  - codeclimate-test-reporter before-build

# command to run tests
script:
   - nosetests --with-coverage --cover-tests
   - coverage report

after_success:
  - coveralls

# after_build:
  - codeclimate-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
