language: python
python:
  - "3.5"

env:
  global:
    - CC_TEST_REPORTER_ID=0a47205c8001662f4a41512154eb2fcf6ff8a65bc5b51909259370038fe57576
# command to install dependencies
install:
  - "pip install -r requirements.txt"

before-script:
  - ./cc-test-reporter before-build

# command to run tests
script:
   - nosetests --with-coverage --cover-tests
   - coverage report

after_success:
  - coveralls

# after_build:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
